name: Syntax Error Check through all python file

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Compile Python sources
        run: >
          python -m compileall
          Client.py Server.py ServerWorker.py VideoStream.py RtpPacket.py
